# Generated by Django 2.0.7 on 2018-07-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20180717_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='disappereance',
            field=models.DateField(blank=True, null=True, verbose_name='Desaparición'),
        ),
    ]
