# Generated by Django 2.0.7 on 2018-07-18 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_auto_20180718_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personimage',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PersonImage',
        ),
    ]
